### ISSUE TITLE
missing timeClient.update()

### ISSUE THREAD

**Issue by jeffeb3** [danielkucera/esp32-oled-clock#1]
I don't the the NTPClient will do any more updates unless you call update() again. Not a huge deal, since you can just reset it to get another update.

This is a great example though. I was looking to do something similar, but with a temperature sensor. I have a similar board, in white. Even the preferences stuff is great to have in there. So thanks.

**Comment by danielkucera** [comment]
https://github.com/danielkucera/esp32-oled-clock/blob/master/src/main.cpp#L25
the last parameter should set automatic update to each 60 seconds but I also noticed that the clock drifts after long usage. I didn't investigate it so far, I used to reset it time to time but would be nice to know why does it not update...

**Comment by jeffeb3** [comment]
I see what you're saying. The way I read their code, the parameter just determines how often update() will call forceUpdate(). NTPClient doesn't spawn a task or anything.

https://github.com/arduino-libraries/NTPClient/blob/master/NTPClient.cpp

**Comment by danielkucera** [comment]
You are right. Fixed in a3c2a8b
